# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Edgie's Veggies
cms_branch: main
cms_repo: jasunde/edgies-veggies
email: edgie@edgiesveggies.com
description: >-
  Small-scale market garden growing delicious salad greens in St. Paul, MN.
  Find us Saturdays at the St. Paul Farmers' Market.
baseurl: ""
url: "https://edgiesveggies.com"
# twitter_username: jekyllrb
github_username:  edgiesveggies

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

host: 0.0.0.0

sass:
  style: compressed
  load_paths:
    - node_modules/uikit/src/scss
  silence_deprecations:
    - import
    - color-functions
    - global-builtin

future: true

collections:
  events:
    output: true
    permalink: /events/:name.ics
  veggies:
    output: true
    permalink: /veggies/:name/
  recipes:
    output: false

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      permalink: /events/:name.ics
  - scope:
      path: ""
      type: "veggies"
    values:
      layout: veggie

exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - netlify.toml
  - _config_staging.yml
